package com.trevornk.ramblr

import android.content.Context
import java.io.BufferedReader
import java.io.InputStream

/**
 * The bundled suggestion-filter dictionary for smart vocabulary suggestions (#216): ~54k common
 * English lemmas, lowercase, one per line, in `res/raw/suggestion_filter_words.txt`. A word's
 * presence here means it is ordinary English and must never be surfaced as a vocabulary
 * suggestion; names ("Hetzner", "Elsinore") are deliberately absent, which is what lets them
 * through. Generated by `tools/generate_suggestion_filter_words.py` (wordfreq top-60k filtered
 * to pure a–z, minus entries the macOS system dictionary lists only capitalized, i.e.
 * proper-noun-shaped) — see that script for full provenance and regeneration steps.
 *
 * This list exists ONLY for suggestion filtering. [VocabularyPostCorrector]'s rewrite guard
 * remains [CommonEnglishWords], sized and tuned separately — the two lists have different
 * jobs (must-not-rewrite vs must-not-suggest) and must not be merged.
 *
 * Loaded lazily into a HashSet on first use (~1 MB retained) and cached for the process
 * lifetime; collection runs on a background thread ([VocabularySuggestionCollector]) so the
 * one-time load never touches the dictation hot path's main thread.
 */
object SuggestionFilterDictionary {

    @Volatile
    private var cached: Set<String>? = null

    /** Whether lowercase [word] is a common English word per the bundled list. */
    fun contains(context: Context, word: String): Boolean = words(context).contains(word)

    fun words(context: Context): Set<String> =
        cached ?: synchronized(this) {
            cached ?: load(context.resources.openRawResource(R.raw.suggestion_filter_words))
                .also { cached = it }
        }

    /** Parses the one-word-per-line stream; blank lines ignored. Closes [stream]. Exposed
     *  separately from [words] so host-side unit tests can load the real repo file without
     *  Android resources. */
    fun load(stream: InputStream): Set<String> =
        stream.bufferedReader().use(BufferedReader::readLines)
            .mapNotNullTo(HashSet(60_000)) { line -> line.trim().ifEmpty { null } }
}
